import puppeteer from 'puppeteer-core';
setTimeout(() => { console.log('TIMEOUT'); process.exit(1); }, 150000);
const [OUT, site = 'ohentpay.com'] = process.argv.slice(2);
const b = await puppeteer.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: true, args: ['--autoplay-policy=no-user-gesture-required'] });
const p = await b.newPage(); const errs = [];
p.on('pageerror', e => errs.push(e.message)); p.on('console', m => { if (m.type() === 'error') errs.push(m.text()); });
await p.setViewport({ width: 1440, height: 900, deviceScaleFactor: 2 });
await p.goto('http://localhost:4600/?url=' + encodeURIComponent(site));
await p.waitForFunction(() => document.querySelector('#loading').hidden && document.querySelector('#menu').hidden, { timeout: 90000 });
const wait = ms => new Promise(r => setTimeout(r, ms));
await wait(2500);
// headline sits near the middle-top of the window: fire the Uzi at it, then minigun
await p.mouse.move(720, 280);
await p.mouse.down(); await wait(900); await p.mouse.up();
await wait(250); await p.screenshot({ path: `${OUT}/let_1.png` });
await p.keyboard.press('Digit2'); await p.mouse.move(820, 300); await p.mouse.down(); await wait(900); await p.mouse.up();
await wait(250); await p.screenshot({ path: `${OUT}/let_2.png` });
await p.keyboard.press('Digit4'); await p.mouse.move(700, 360); await p.mouse.down(); await wait(60); await p.mouse.up();
await wait(700); await p.screenshot({ path: `${OUT}/let_3.png` });
console.log('errors:', errs.join(' | ') || 'none'); await b.close(); process.exit(0);
